# ===================================================================
# SONARCLOUD CONFIGURATION
# ===================================================================

# Información del proyecto
sonar.projectKey=MiguelRodriguez09_Final-ML---Dspliegue-MLOps
sonar.organization=miguelrodriguez09

# Nombre y versión del proyecto
sonar.projectName=Final-ML-Despliegue-MLOps
sonar.projectVersion=1.0

# Directorio de código fuente
sonar.sources=mlops_pipeline/src
sonar.sourceEncoding=UTF-8

# Lenguajes a analizar
sonar.language=py

# Exclusiones (archivos que no se deben analizar)
sonar.exclusions=\
  **/Proyecto-venv/**,\
  **/__pycache__/**,\
  **/.ipynb_checkpoints/**,\
  **/node_modules/**,\
  **/dist/**,\
  **/build/**,\
  **/*.ipynb,\
  **/tests/**,\
  **/data/**,\
  **/models/**,\
  **/reports/**,\
  **/monitoring/**

# Cobertura de tests (si tienes tests)
# sonar.python.coverage.reportPaths=coverage.xml
# sonar.python.xunit.reportPath=xunit-result.xml

# Configuración de Python
sonar.python.version=3.13

# Nivel de log
sonar.log.level=INFO

# Configuración de análisis
sonar.qualitygate.wait=true
