sonar.projectKey=MiguelRodriguez09_Final-ML---Dspliegue-MLOps
sonar.organization=miguelrodriguez09

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Final-ML---Dspliegue-MLOps
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=mlops_pipeline/src

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=py

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.ipynb,**/venv/**,**/env/**

# Python specific settings
sonar.python.version=3.10
